export const mockInventoryData = [
  {
    id: 1,
    code: "MCU-32F103",
    description: "32-bit Microcontroller ARM Cortex",
    part_grade: "Industrial",
    component_classification: "IC",
    revision: "Rev B",
    msl_level: "MSL 3",
    category: "Semiconductor",
    uom: "pcs",
    standard_cost: 290.45,
    lead_time: 45,
    quantity: 1500,
    status: "Active"
  },
  {
    id: 2,
    code: "CAP-0805-10U",
    description: "10uF 16V Ceramic Capacitor 0805",
    part_grade: "Commercial",
    component_classification: "Passive",
    revision: "-",
    msl_level: "MSL 1",
    category: "Capacitor",
    uom: "reel",
    standard_cost: 1250.20,
    lead_time: 14,
    quantity: 42,
    status: "Active"
  },
  {
    id: 3,
    code: "RES-0603-10K",
    description: "10K Ohm 1% 1/10W Resistor 0603",
    part_grade: "Automotive",
    component_classification: "Passive",
    revision: "A.1",
    msl_level: "MSL 1",
    category: "Resistor",
    uom: "reel",
    standard_cost: 650.50,
    lead_time: 14,
    quantity: 120,
    status: "Active"
  },
  {
    id: 4,
    code: "CON-USB-C",
    description: "USB Type-C Receptacle SMD",
    part_grade: "Commercial",
    component_classification: "Connector",
    revision: "v2.0",
    msl_level: "MSL 1",
    category: "Connector",
    uom: "pcs",
    standard_cost: 70.85,
    lead_time: 21,
    quantity: 8,
    status: "Active"
  },
  {
    id: 5,
    code: "PCB-MAIN-01",
    description: "Main Control Board Bare PCB",
    part_grade: "Custom",
    component_classification: "PCB",
    revision: "V1.4",
    msl_level: "-",
    category: "PCB",
    uom: "pcs",
    standard_cost: 1050.40,
    lead_time: 28,
    quantity: 3,
    status: "Obsolete"
  },
  {
    id: 6,
    code: "PWR-5V-2A",
    description: "5V 2A DC-DC Converter Module",
    part_grade: "Industrial",
    component_classification: "Power",
    revision: "Rev A",
    msl_level: "MSL 2",
    category: "Power Supply",
    uom: "pcs",
    standard_cost: 495.90,
    lead_time: 30,
    quantity: 340,
    status: "Active"
  }
];